### ISSUE TITLE
generate picture thumbnail failed

### ISSUE THREAD

**Issue by wyy0117** [liferay/liferay-docker#47]
I tried the image version:liferay/portal:6.2.5-ga6,and the image default jdk is openJDK,if upload a pciture and will throw exception just like:
`Exception in thread "liferay/document_library_image_processor-1" java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
	at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
	at com.sun.media.jai.codec.ImageDecoderImpl.decodeAsRenderedImage(ImageDecoderImpl.java:140)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:580)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:424)
	at com.liferay.portal.kernel.image.ImageToolUtil.read(ImageToolUtil.java:183)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl._generateImages(ImageProcessorImpl.java:283)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl.generateImages(ImageProcessorImpl.java:81)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorUtil.generateImages(ImageProcessorUtil.java:53)
	at com.liferay.portlet.documentlibrary.messaging.ImageProcessorMessageListener.generate(ImageProcessorMessageListener.java:31)
	at com.liferay.portlet.documentlibrary.messaging.BaseProcessorMessageListener.doReceive(BaseProcessorMessageListener.java:36)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:67)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 16 more
Exception in thread "liferay/document_library_image_processor-2" java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
	at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
	at com.sun.media.jai.codec.ImageDecoderImpl.decodeAsRenderedImage(ImageDecoderImpl.java:140)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:580)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:424)
	at com.liferay.portal.kernel.image.ImageToolUtil.read(ImageToolUtil.java:183)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl._generateImages(ImageProcessorImpl.java:283)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl.generateImages(ImageProcessorImpl.java:81)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorUtil.generateImages(ImageProcessorUtil.java:53)
	at com.liferay.portlet.documentlibrary.messaging.ImageProcessorMessageListener.generate(ImageProcessorMessageListener.java:31)
	at com.liferay.portlet.documentlibrary.messaging.BaseProcessorMessageListener.doReceive(BaseProcessorMessageListener.java:36)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:67)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 16 more
`
yes,this is because liferay generate thumbnail used some oracle jdk features,and I can create a new image use oracle jdk to fix it.But is this the best practice?

**Comment by zsoltbalogh** [comment]
Hi @wyy0117 ,

Thank you for reporting the issue. I've looked up the various tickets (e.g. https://issues.liferay.com/browse/LPS-29365) and it seems that this issue should have been fixed in the portal code. Unfortunately there are some reports which claim that in the CE Portal version this was not resolved (https://issues.liferay.com/browse/LPS-62358), this doesn't help to resolve the situation. :(

As we are not planning to make any more 6.2.x releases and we cannot add the Oracle JDK to our images currently, there's only two options:
(1) You fix the problem on the portal code and ensure this problem is fixed
(2) You install the Oracle JDK in a new layer on the top of the images. 

If you choose the 2nd, please just put it to /usr/lib/jvm/[anything] folder and start the JVM with the JAVA_VERSION=[anything]  environment variable.

I know this is not much, but hoping they help. Circumstances (no more release, Oracle JDK limitations) are not allowing me to do more. Please let me know if you have any questions.

I have noticed that you are opening more tickets, it'd be great if you could open these tickets in http://issues.liferay.com/ under the LPS project with the Docker Images component - we would have more visibility of these issues there. 

Thanks,
Zsolt

Zsolt
