### ISSUE TITLE
TLS 1.2 issues

### ISSUE THREAD

**Issue by davidcodesido** [liferay/liferay-docker#73]
I'm using 7.3.7-ga8 and also tried 7.3.7-ga8-d1.6.2-20210628090302 (not sure what the difference is). 

When trying to connect to smtp.office365.com to send an email I'm getting the following exception:

```
2021-06-30 23:15:34.640 ERROR [http-nio-8080-exec-3][MailEngine:128] Unable to send message: Could not connect to SMTP host: smtp.office365.com, port: 587
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:449)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1409)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1315)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:439)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:410)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
	at javax.mail.Service.connect(Service.java:342)
	at com.liferay.petra.mail.MailEngine._send(MailEngine.java:613)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:389)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:192)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:179)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:424)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:144)
	at com.liferay.petra.mail.MailEngine.send(MailEngine.java:478)
```

I think I have tied it down to an update in Microsoft side disabling some ciphering suites and enforcing TLS 1.2. I see that the last commits here in master refer the use of TLS 1.3. How can I get this images? The ones from docker hub published from 2 days ago are the ones I'm using but still getting this error. Any help will be welcome.

**Comment by davidcodesido** [comment]
Also tried JAVA_VERSION=zulu11 with no luck. Same exception.

**Comment by davidcodesido** [comment]
Fixed this by disabling SSL when connecting to the smtp server (this was my fault) and using the jvm flag -XX:+UseOpenJSSE This enables the newest protocols in Java 8 when connecting to backends that only support newest TLS ciphering suites.
